# Minimum Example: Fetching a Dimension Table

This notebook shows the shortest path to fetching a Census group and displaying it as a dimension table.

In [1]:
from morpc_census import Endpoint, CensusAPI, DimensionTable

## 1. Build an Endpoint

An `Endpoint` pairs a survey name with a vintage year.

In [2]:
ep = Endpoint('dec/pl', 2020)

## 2. Fetch the data

`CensusAPI` takes an endpoint, a scope, and a group code. Here we fetch **B02001** (Race) for the 15-county MORPC region.

In [3]:
api = CensusAPI(ep, 'region15', group='P1')
api.long

,geoidfq,name,reference_period,survey,concept,universe,variable_label,variable,total
0,0500000US39041,"Delaware County, Ohio",2020,dec/pl,Race,Total population,Total:,P1_001,214124.0
1,0500000US39041,"Delaware County, Ohio",2020,dec/pl,Race,Total population,Total:!!Population of one race:,P1_002,202146.0
7,0500000US39041,"Delaware County, Ohio",2020,dec/pl,Race,Total population,Total:!!Population of one race:!!White alone,P1_003,173231.0
4,0500000US39041,"Delaware County, Ohio",2020,dec/pl,Race,Total population,Total:!!Population of one race:!!Black or Afri...,P1_004,7840.0
2,0500000US39041,"Delaware County, Ohio",2020,dec/pl,Race,Total population,Total:!!Population of one race:!!American Indi...,P1_005,324.0
...,...,...,...,...,...,...,...,...,...
1009,0500000US39159,"Union County, Ohio",2020,dec/pl,Race,Total population,Total:!!Population of two or more races:!!Popu...,P1_067,0.0
1005,0500000US39159,"Union County, Ohio",2020,dec/pl,Race,Total population,Total:!!Population of two or more races:!!Popu...,P1_068,0.0
1004,0500000US39159,"Union County, Ohio",2020,dec/pl,Race,Total population,Total:!!Population of two or more races:!!Popu...,P1_069,0.0
1026,0500000US39159,"Union County, Ohio",2020,dec/pl,Race,Total population,Total:!!Population of two or more races:!!Popu...,P1_070,0.0
1027,0500000US39159,"Union County, Ohio",2020,dec/pl,Race,Total population,Total:!!Population of two or more races:!!Popu...,P1_071,0.0

## 3. Display as a DimensionTable

`DimensionTable` parses the `!!`-delimited variable labels into named columns and pivots to a wide layout. B02001 has two label levels: a grand total and a race category.

In [4]:
dim = DimensionTable(api.long)
dim.wide()

concept                                                                                                                                           Race  \
universe                                                                                                                              Total population
survey                                                                                                                                          dec/pl
geoidfq                                                                                                                                 0500000US39041
name                                                                                                                             Delaware County, Ohio
reference_period                                                                                                                                  2020
value_type                                                                                                                                       total
Total Race                            Race 2                                  Race 3
Total                                                                                                                                         214124.0
      Population of one race                                                                                                                  202146.0
                                      White alone                                                                                             173231.0
                                      Black or African American alone                                                                           7840.0
                                      American Indian and Alaska Native alone                                                                    324.0
...                                                                                                                                                ...
      Population of two or more races Population of five races                White; Black or African American; Asian; Native...                   0.0
                                                                              White; American Indian and Alaska Native; Asian...                   0.0
                                                                              Black or African American; American Indian and ...                   0.0
                                      Population of six races                                                                                      0.0
                                                                              White; Black or African American; American Indi...                   0.0

concept                                                                                                                                                  \
universe
survey
geoidfq                                                                                                                                  0500000US39045
name                                                                                                                             Fairfield County, Ohio
reference_period                                                                                                                                   2020
value_type                                                                                                                                        total
Total Race                            Race 2                                  Race 3
Total                                                                                                                                          158921.0
      Population of one race                                                                                                                   150291.0
                                      White alone                                                                                              131676.0
                                      Black or African American alone                                                                           13484.0
                                      American Indian and Alaska Native alone                                                                     378.0
...                                                                                                                                                 ...
      Population of two or more races Population of five races                White; Black or African American; Asian; Native...                    0.0
                                                                              White; American Indian and Alaska Native; Asian...                    0.0
                                                                              Black or African American; American Indian and ...                    0.0
                                      Population of six races                                                                                       1.0
                                                                              White; Black or African American; American Indi...                    1.0

concept                                                                                                                                                \
universe
survey
geoidfq                                                                                                                                0500000US39047
name                                                                                                                             Fayette County, Ohio
reference_period                                                                                                                                 2020
value_type                                                                                                                                      total
Total Race                            Race 2                                  Race 3
Total                                                                                                                                         28951.0
      Population of one race                                                                                                                  27552.0
                                      White alone                                                                                             26523.0
                                      Black or African American alone                                                                           543.0
                                      American Indian and Alaska Native alone                                                                    69.0
...                                                                                                                                               ...
      Population of two or more races Population of five races                White; Black or African American; Asian; Native...                  0.0
                                                                              White; American Indian and Alaska Native; Asian...                  0.0
                                                                              Black or African American; American Indian and ...                  0.0
                                      Population of six races                                                                                     2.0
                                                                              White; Black or African American; American Indi...                  2.0

concept                                                                                                                                                 \
universe
survey
geoidfq                                                                                                                                 0500000US39049
name                                                                                                                             Franklin County, Ohio
reference_period                                                                                                                                  2020
value_type                                                                                                                                       total
Total Race                            Race 2                                  Race 3
Total                                                                                                                                        1323807.0
      Population of one race                                                                                                                 1230708.0
                                      White alone                                                                                             802685.0
                                      Black or African American alone                                                                         299771.0
                                      American Indian and Alaska Native alone                                                                   4564.0
...                                                                                                                                                ...
      Population of two or more races Population of five races                White; Black or African American; Asian; Native...                   7.0
                                                                              White; American Indian and Alaska Native; Asian...                   0.0
                                                                              Black or African American; American Indian and ...                   0.0
                                      Population of six races                                                                                      0.0
                                                                              White; Black or African American; American Indi...                   0.0

concept                                                                                                                                                \
universe
survey
geoidfq                                                                                                                                0500000US39073
name                                                                                                                             Hocking County, Ohio
reference_period                                                                                                                                 2020
value_type                                                                                                                                      total
Total Race                            Race 2                                  Race 3
Total                                                                                                                                         28050.0
      Population of one race                                                                                                                  26946.0
                                      White alone                                                                                             26595.0
                                      Black or African American alone                                                                           140.0
                                      American Indian and Alaska Native alone                                                                    50.0
...                                                                                                                                               ...
      Population of two or more races Population of five races                White; Black or African American; Asian; Native...                  0.0
                                                                              White; American Indian and Alaska Native; Asian...                  0.0
                                                                              Black or African American; American Indian and ...                  0.0
                                      Population of six races                                                                                     0.0
                                                                              White; Black or African American; American Indi...                  0.0

concept                                                                                                                                             \
universe
survey
geoidfq                                                                                                                             0500000US39083
name                                                                                                                             Knox County, Ohio
reference_period                                                                                                                              2020
value_type                                                                                                                                   total
Total Race                            Race 2                                  Race 3
Total                                                                                                                                      62721.0
      Population of one race                                                                                                               60100.0
                                      White alone                                                                                          58400.0
                                      Black or African American alone                                                                        566.0
                                      American Indian and Alaska Native alone                                                                147.0
...                                                                                                                                            ...
      Population of two or more races Population of five races                White; Black or African American; Asian; Native...               0.0
                                                                              White; American Indian and Alaska Native; Asian...               0.0
                                                                              Black or African American; American Indian and ...               0.0
                                      Population of six races                                                                                  0.0
                                                                              White; Black or African American; American Indi...               0.0

concept                                                                                                                                                \
universe
survey
geoidfq                                                                                                                                0500000US39089
name                                                                                                                             Licking County, Ohio
reference_period                                                                                                                                 2020
value_type                                                                                                                                      total
Total Race                            Race 2                                  Race 3
Total                                                                                                                                        178519.0
      Population of one race                                                                                                                 168745.0
                                      White alone                                                                                            154070.0
                                      Black or African American alone                                                                          7213.0
                                      American Indian and Alaska Native alone                                                                   452.0
...                                                                                                                                               ...
      Population of two or more races Population of five races                White; Black or African American; Asian; Native...                  0.0
                                                                              White; American Indian and Alaska Native; Asian...                  0.0
                                                                              Black or African American; American Indian and ...                  0.0
                                      Population of six races                                                                                     0.0
                                                                              White; Black or African American; American Indi...                  0.0

concept                                                                                                                                              \
universe
survey
geoidfq                                                                                                                              0500000US39091
name                                                                                                                             Logan County, Ohio
reference_period                                                                                                                               2020
value_type                                                                                                                                    total
Total Race                            Race 2                                  Race 3
Total                                                                                                                                       46150.0
      Population of one race                                                                                                                43617.0
                                      White alone                                                                                           42049.0
                                      Black or African American alone                                                                         677.0
                                      American Indian and Alaska Native alone                                                                  99.0
...                                                                                                                                             ...
      Population of two or more races Population of five races                White; Black or African American; Asian; Native...                1.0
                                                                              White; American Indian and Alaska Native; Asian...                0.0